backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'agendas' # Used in routes, e.g., /admin/collections/blog
    label: 'Agendas' # Used in the UI
    folder: 'site/studio/agendas' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }